### PR TITLE
[FIX] #2 change header text content + delete menu icon

### LINKED ISSUE #2: Header fixes.
image

1.  - [x] Remove left button
2.  - [ ] Update project name
3.  - [ ] fix right icon margin (seems too large)

### PR DESCRIPTION
**Pull request by AndreAffonso**
### Description 
closes #2
- Centralized text content
- Deleted Menu icon

### Screenshot

Landing Page |Table Page| 
|-------------------|---------------|
| ||

### CODE REVIEW

File: app/containers/Company/reducer.js [hunk 1]
```diff
@@ -1,20 +1,19 @@
...
+  name: 'Mive',
 });
 
 function companyReducer(state = initialState, action) {
   switch (action.type) {
     case FETCH_COMPANY_INFO:
       return handle(state, action, {
-        start: () => (fromJS({ isLoading: true })),
-        finish: () => (fromJS({ ...action.payload.data(), isLoading: false })), // TODO Use success lifecycle from redux-pack
+        start: () => fromJS({ isLoading: true }),
```
Comment (brunobraga95) [inline app/containers/Company/reducer.js:15]: is there a reason why you removed this?

**Review by brunobraga95 — APPROVED** [review]
